"""Data-access API: import from core.db. Every call reads core.config.DB_PATH; mock DB functions in the module that uses them."""
from core.db.connection import get_connection
from core.db.schema import init_db
from core.db.events import (
    insert_event,
    update_event_status,
    update_event_field,
    delete_event,
    get_event,
    get_event_by_telegram_message_id,
    get_event_by_discussion_message_id,
    get_event_by_admin_message_id,
    get_pending_events_for_recap,
    mark_events_as_recap,
    update_events_wp_info,
    update_telegram_message_info,
    update_discussion_message_info,
    get_approved_events_for_date,
    get_upcoming_events,
)
from core.db.reservations import (
    get_reservations_for_event,
    get_reservation,
    get_reservation_by_user,
    get_user_conflicting_events,
)
from core.db.seats import (
    book_seat,
    unbook_seat,
    admin_add_seat,
    admin_remove_seat,
    admin_add_subscriber,
    admin_remove_subscriber,
)
from core.db.scheduled import (
    insert_scheduled_event,
    get_scheduled_event,
    get_all_scheduled_events,
    update_scheduled_event_days,
    update_scheduled_event_specific_date,
    update_scheduled_event_content,
    delete_scheduled_event,
    get_scheduled_events_for_date,
)

__all__ = [
    "insert_event",
    "update_event_status",
    "update_event_field",
    "delete_event",
    "get_event",
    "get_event_by_telegram_message_id",
    "get_event_by_discussion_message_id",
    "get_event_by_admin_message_id",
    "get_pending_events_for_recap",
    "mark_events_as_recap",
    "update_events_wp_info",
    "update_telegram_message_info",
    "update_discussion_message_info",
    "get_approved_events_for_date",
    "get_upcoming_events",
    "get_reservations_for_event",
    "get_reservation",
    "get_reservation_by_user",
    "get_user_conflicting_events",
    "book_seat",
    "unbook_seat",
    "admin_add_seat",
    "admin_remove_seat",
    "admin_add_subscriber",
    "admin_remove_subscriber",
    "insert_scheduled_event",
    "get_scheduled_event",
    "get_all_scheduled_events",
    "update_scheduled_event_days",
    "update_scheduled_event_specific_date",
    "update_scheduled_event_content",
    "delete_scheduled_event",
    "get_scheduled_events_for_date",
    "get_connection",
    "init_db",
]
